export const DEFAULT_THEME_ID = 'light';

export const themes = {
  light: {
    id: 'light',
    name: 'Light',
    colors: {
      primary: '#4F46E5',
      primaryDark: '#4338CA',
      secondary: '#22C55E',
      accent: '#F59E0B',
      danger: '#EF4444',
      background: '#F6F7FB',
      surface: '#FFFFFF',
      surfaceAlt: '#F1F3F8',
      text: '#0F172A',
      textMuted: '#64748B',
      border: '#E2E8F0',
      chip: '#EEF2FF',
      chatBubble: '#EEF2FF',
    },
  },
  dark: {
    id: 'dark',
    name: 'Dark',
    colors: {
      primary: '#8B9CFF',
      primaryDark: '#6D7BFF',
      secondary: '#6EE7B7',
      accent: '#FCD34D',
      danger: '#F87171',
      background: '#0B1020',
      surface: '#121A2E',
      surfaceAlt: '#0F1628',
      text: '#F1F5F9',
      textMuted: '#94A3B8',
      border: '#1F2A44',
      chip: '#1B2550',
      chatBubble: '#1B2550',
    },
  },
  pastelSky: {
    id: 'pastelSky',
    name: 'Pastel Sky',
    colors: {
      primary: '#6C9BF6',
      primaryDark: '#5A86E6',
      secondary: '#7ED6C5',
      accent: '#F7C78B',
      danger: '#F59BA4',
      background: '#F7FAFF',
      surface: '#FFFFFF',
      surfaceAlt: '#EFF4FF',
      text: '#21314F',
      textMuted: '#6B7C99',
      border: '#E3E9F5',
      chip: '#EAF1FF',
      chatBubble: '#EAF1FF',
    },
  },
  pastelRose: {
    id: 'pastelRose',
    name: 'Pastel Rose',
    colors: {
      primary: '#E7A0B3',
      primaryDark: '#D4879E',
      secondary: '#A8E6CF',
      accent: '#F4D7B6',
      danger: '#F2A5A5',
      background: '#FFF7F9',
      surface: '#FFFFFF',
      surfaceAlt: '#FFEFF4',
      text: '#3D2C35',
      textMuted: '#7A6672',
      border: '#F1D8E2',
      chip: '#FFE5EC',
      chatBubble: '#FFE5EC',
    },
  },
  pastelMint: {
    id: 'pastelMint',
    name: 'Pastel Mint',
    colors: {
      primary: '#8ECFD2',
      primaryDark: '#76BAC0',
      secondary: '#B5EAD7',
      accent: '#F8DFAF',
      danger: '#F4A7A7',
      background: '#F6FFFD',
      surface: '#FFFFFF',
      surfaceAlt: '#EFFFFB',
      text: '#20323A',
      textMuted: '#6B7B82',
      border: '#DCEFEB',
      chip: '#E7FAF5',
      chatBubble: '#E7FAF5',
    },
  },
};

export const getTheme = (themeId) => themes[themeId] || themes[DEFAULT_THEME_ID];

export const radii = {
  sm: 10,
  md: 14,
  lg: 18,
  xl: 22,
};

export const shadows = {
  soft: {
    shadowColor: '#0F172A',
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  card: {
    shadowColor: '#0F172A',
    shadowOpacity: 0.12,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
};
